/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import java.awt.Image;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Conexion;
import modelo.IngresarVenta;
import modelo.IngresoUsuario;
import modelo.MantenedorProducto;
import modelo.RegistroVentas;
import negocio.Disco;
import negocio.Poster;
import negocio.Producto;
import negocio.Venta;

/**
 *
 * @author jhon_
 */
public class NewJFrame extends javax.swing.JFrame {
    //100 filas y 5 columnas
    String [][] matrizPoster = new String[100][4];
    String [][] matrizDisco = new String[100][5];
    String [][] matrizVenta = new String[100][2];    
    DefaultTableModel modelo;
    
    //Consigue el máximo idInterno de la tabla venta
    IngresarVenta vent = new IngresarVenta();
    int idInterno;
    IngresoUsuario ingUs = new IngresoUsuario();
    /**
     * Creates new form NewJFrame
     * @throws java.sql.SQLException
     */
    public NewJFrame() throws SQLException {
        this.idInterno = vent.idInternoActual();
        initComponents();
        tabPane.enable(false);
        lblMensajeIngreso.setVisible(false);
        setIconImage(new ImageIcon(getClass().getResource("/iconos/iconoesquina.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        tabPane = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtIngresoUsuario = new javax.swing.JTextField();
        pwdIngresoContrasena = new javax.swing.JPasswordField();
        btnIngresoUsuario = new javax.swing.JButton();
        lblMensajeIngreso = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPoster = new javax.swing.JTable();
        btnListarDisco = new javax.swing.JButton();
        btnBuscarProducto = new javax.swing.JButton();
        btnListarPoster = new javax.swing.JButton();
        btnInsertarProducto = new javax.swing.JButton();
        txtPrecioInsertar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombreInsertar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCodigoInsertar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        radPoster = new javax.swing.JRadioButton();
        radDisco = new javax.swing.JRadioButton();
        txtDimensionesInsertar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtArtistaInsertar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        asas = new javax.swing.JLabel();
        txtAnnioInsertar = new javax.swing.JTextField();
        btnEliminarProducto = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDisco = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNumeroVentaInsertar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtProductoInsertar = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txaImprimirVenta = new javax.swing.JTextArea();
        txtImprimir = new javax.swing.JButton();
        txtIngresarVenta = new javax.swing.JButton();
        txtFechaInsertar = new com.toedter.calendar.JDateChooser();
        jPanel5 = new javax.swing.JPanel();
        btnListarVenta = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        txaRegistroVentas = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel9.setText("¡Bienvenido/a a la aplicación de ventas de discos y posters!");

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel10.setText("Usuario");

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel11.setText("Contraseña");

        txtIngresoUsuario.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtIngresoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIngresoUsuarioActionPerformed(evt);
            }
        });

        pwdIngresoContrasena.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        btnIngresoUsuario.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnIngresoUsuario.setText("Acceder");
        btnIngresoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresoUsuarioActionPerformed(evt);
            }
        });

        lblMensajeIngreso.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblMensajeIngreso.setText("Mensaje de entrada");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/usuario.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblMensajeIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(305, 305, 305))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel9))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(380, 380, 380)
                        .addComponent(btnIngresoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIngresoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pwdIngresoContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(240, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel9)
                .addGap(75, 75, 75)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtIngresoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(pwdIngresoContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(btnIngresoUsuario)
                .addGap(18, 18, 18)
                .addComponent(lblMensajeIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
        );

        tabPane.addTab("Ingreso", jPanel6);

        tblPoster.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPoster.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPosterMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPoster);

        btnListarDisco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/listar.png"))); // NOI18N
        btnListarDisco.setText("Listar Disco");
        btnListarDisco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarDiscoActionPerformed(evt);
            }
        });

        btnBuscarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/buscar.png"))); // NOI18N
        btnBuscarProducto.setText("Buscar");
        btnBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProductoActionPerformed(evt);
            }
        });

        btnListarPoster.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/listar.png"))); // NOI18N
        btnListarPoster.setText("Listar Poster");
        btnListarPoster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarPosterActionPerformed(evt);
            }
        });

        btnInsertarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/guardar.png"))); // NOI18N
        btnInsertarProducto.setText("Guardar");
        btnInsertarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarProductoActionPerformed(evt);
            }
        });

        txtPrecioInsertar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPrecioInsertarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPrecioInsertarFocusLost(evt);
            }
        });
        txtPrecioInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioInsertarActionPerformed(evt);
            }
        });

        jLabel3.setText("Precio");

        txtNombreInsertar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNombreInsertarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreInsertarFocusLost(evt);
            }
        });

        jLabel2.setText("Nombre");

        txtCodigoInsertar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCodigoInsertarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodigoInsertarFocusLost(evt);
            }
        });
        txtCodigoInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoInsertarActionPerformed(evt);
            }
        });

        jLabel1.setText("Codigo");

        buttonGroup1.add(radPoster);
        radPoster.setText("Poster");
        radPoster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radPosterActionPerformed(evt);
            }
        });

        buttonGroup1.add(radDisco);
        radDisco.setText("Disco");
        radDisco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radDiscoActionPerformed(evt);
            }
        });

        txtDimensionesInsertar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDimensionesInsertarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDimensionesInsertarFocusLost(evt);
            }
        });

        jLabel4.setText("Dimensiones");

        txtArtistaInsertar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtArtistaInsertarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtArtistaInsertarFocusLost(evt);
            }
        });

        jLabel5.setText("Artista");

        asas.setText("Año");

        txtAnnioInsertar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAnnioInsertarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAnnioInsertarFocusLost(evt);
            }
        });

        btnEliminarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/eliminar.png"))); // NOI18N
        btnEliminarProducto.setText("Eliminar");
        btnEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProductoActionPerformed(evt);
            }
        });

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/editar.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        tblDisco.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDisco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDiscoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblDisco);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNombreInsertar))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(20, 20, 20)
                                .addComponent(txtPrecioInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(radPoster)
                                        .addGap(18, 18, 18)
                                        .addComponent(radDisco))
                                    .addComponent(txtCodigoInsertar))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(btnListarPoster)
                                .addGap(105, 105, 105)
                                .addComponent(btnInsertarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnBuscarProducto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(asas)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAnnioInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDimensionesInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtArtistaInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(btnListarDisco)))
                .addGap(137, 137, 137))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDimensionesInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtArtistaInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(asas)
                            .addComponent(txtAnnioInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnListarDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(radPoster)
                                    .addComponent(radDisco))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txtCodigoInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtNombreInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtPrecioInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addComponent(btnListarPoster, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEliminarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnInsertarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        tabPane.addTab("Mantenedor Producto", jPanel2);

        jLabel6.setText("N° Venta");

        jLabel7.setText("Fecha");

        txtNumeroVentaInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroVentaInsertarActionPerformed(evt);
            }
        });

        jLabel8.setText("Producto (Codigo)");

        txaImprimirVenta.setColumns(20);
        txaImprimirVenta.setRows(5);
        jScrollPane3.setViewportView(txaImprimirVenta);

        txtImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/imprimir.png"))); // NOI18N
        txtImprimir.setText("Imprimir Venta Actual");
        txtImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImprimirActionPerformed(evt);
            }
        });

        txtIngresarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/agregar.png"))); // NOI18N
        txtIngresarVenta.setText("Agregar Producto a Venta");
        txtIngresarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIngresarVentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(txtNumeroVentaInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(39, 39, 39)
                                        .addComponent(txtImprimir))
                                    .addComponent(txtProductoInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(txtFechaInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtIngresarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(141, 141, 141)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(216, 216, 216))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtNumeroVentaInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(txtFechaInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtProductoInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addComponent(txtIngresarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        tabPane.addTab("Ingresar Venta", jPanel3);

        btnListarVenta.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnListarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/registro.png"))); // NOI18N
        btnListarVenta.setText("Listar Ventas");
        btnListarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarVentaActionPerformed(evt);
            }
        });

        txaRegistroVentas.setColumns(20);
        txaRegistroVentas.setRows(5);
        jScrollPane5.setViewportView(txaRegistroVentas);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(btnListarVenta)
                .addGap(66, 66, 66)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(220, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                .addGap(95, 95, 95))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(btnListarVenta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabPane.addTab("Registro de Ventas", jPanel5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPane)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPane)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoInsertarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoInsertarFocusGained

    }//GEN-LAST:event_txtCodigoInsertarFocusGained

    private void txtPrecioInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioInsertarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioInsertarActionPerformed

    private void btnInsertarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarProductoActionPerformed
        try{
            Poster poster = new Poster();
            Disco disco = new Disco();
            MantenedorProducto con = new MantenedorProducto();

            //El if
            if(radPoster.isSelected())
            {
                txtAnnioInsertar.setText("");
                txtArtistaInsertar.setText("");
                poster.setCodigo(txtCodigoInsertar.getText());
                poster.setNombre(txtNombreInsertar.getText());
                poster.setPrecio(Integer.parseInt(txtPrecioInsertar.getText()));
                poster.setDimension(txtDimensionesInsertar.getText());
                con.insertarPoster(poster);
                JOptionPane.showMessageDialog(null, "Producto Ingresado");
                txtCodigoInsertar.requestFocus();
                limpiarControles();
                
            }

            else if(radDisco.isSelected())
            {
                txtDimensionesInsertar.setText("");                
                disco.setCodigo(txtCodigoInsertar.getText());
                disco.setNombre(txtNombreInsertar.getText());
                disco.setPrecio(Integer.parseInt(txtPrecioInsertar.getText()));
                disco.setArtista(txtArtistaInsertar.getText());
                disco.setAnnio(Integer.parseInt(txtAnnioInsertar.getText()));
                con.insertarDisco(disco);
                JOptionPane.showMessageDialog(null, "Producto Ingresado");
                txtCodigoInsertar.requestFocus();
                limpiarControles();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Debe  seleccionar el tipo de producto");
            }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_btnInsertarProductoActionPerformed

    private void radDiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radDiscoActionPerformed
        limpiarControles();
        txtCodigoInsertar.setFocusable(true);
        txtCodigoInsertar.setForeground(Color.black);
        txtNombreInsertar.setFocusable(true);
        txtNombreInsertar.setForeground(Color.black);
        txtPrecioInsertar.setFocusable(true);
        txtPrecioInsertar.setForeground(Color.black);
        txtDimensionesInsertar.setFocusable(false);
        txtDimensionesInsertar.setForeground(Color.gray);
        txtArtistaInsertar.setFocusable(true);
        txtArtistaInsertar.setForeground(Color.black);
        txtAnnioInsertar.setFocusable(true);
        txtAnnioInsertar.setForeground(Color.black);
        btnInsertarProducto.setEnabled(true);
    }//GEN-LAST:event_radDiscoActionPerformed

    private void radPosterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radPosterActionPerformed
        limpiarControles();
        txtCodigoInsertar.setFocusable(true);
        txtCodigoInsertar.setForeground(Color.black);
        txtNombreInsertar.setFocusable(true);
        txtNombreInsertar.setForeground(Color.black);
        txtPrecioInsertar.setFocusable(true);
        txtPrecioInsertar.setForeground(Color.black);
        txtDimensionesInsertar.setFocusable(true);
        txtDimensionesInsertar.setForeground(Color.black);
        txtArtistaInsertar.setFocusable(false);
        txtArtistaInsertar.setForeground(Color.gray);
        txtAnnioInsertar.setFocusable(false);
        txtAnnioInsertar.setForeground(Color.gray);
        btnInsertarProducto.setEnabled(true);
    }//GEN-LAST:event_radPosterActionPerformed

    private void btnListarPosterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarPosterActionPerformed
        try {
            int fila=0;
            String [] titulos = {"Codigo","Nombre","Precio","Dimension"};
            MantenedorProducto con = new MantenedorProducto();
            ArrayList<Poster> listarposter = con.listarPoster();
            for (Poster poster:listarposter)
            {
                matrizPoster[fila][0]= poster.getCodigo();
                matrizPoster[fila][1]= poster.getNombre();
                matrizPoster[fila][2]= String.valueOf(poster.getPrecio());
                matrizPoster[fila][3]= poster.getDimension();
                fila++;
            }
            modelo = new DefaultTableModel(matrizPoster,titulos);
            tblPoster.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
                                            

    }//GEN-LAST:event_btnListarPosterActionPerformed

    private void txtCodigoInsertarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoInsertarFocusLost

        
    }//GEN-LAST:event_txtCodigoInsertarFocusLost

    private void txtNombreInsertarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreInsertarFocusGained

    }//GEN-LAST:event_txtNombreInsertarFocusGained

    private void txtNombreInsertarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreInsertarFocusLost

    }//GEN-LAST:event_txtNombreInsertarFocusLost

    private void txtPrecioInsertarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPrecioInsertarFocusGained

    }//GEN-LAST:event_txtPrecioInsertarFocusGained

    private void txtPrecioInsertarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPrecioInsertarFocusLost

    }//GEN-LAST:event_txtPrecioInsertarFocusLost

    private void txtDimensionesInsertarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDimensionesInsertarFocusGained

    }//GEN-LAST:event_txtDimensionesInsertarFocusGained

    private void txtDimensionesInsertarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDimensionesInsertarFocusLost

    }//GEN-LAST:event_txtDimensionesInsertarFocusLost

    private void txtArtistaInsertarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtArtistaInsertarFocusGained

    }//GEN-LAST:event_txtArtistaInsertarFocusGained

    private void txtArtistaInsertarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtArtistaInsertarFocusLost

    }//GEN-LAST:event_txtArtistaInsertarFocusLost

    private void txtAnnioInsertarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAnnioInsertarFocusGained

    }//GEN-LAST:event_txtAnnioInsertarFocusGained

    private void txtAnnioInsertarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAnnioInsertarFocusLost

    }//GEN-LAST:event_txtAnnioInsertarFocusLost

    private void btnListarDiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarDiscoActionPerformed
        try {
            int fila=0;
            String [] titulos = {"Codigo","Nombre","Precio","Artista","Año"};
            MantenedorProducto con = new MantenedorProducto();
            ArrayList<Disco> listardisco = con.listarDisco();
            for (Disco disco:listardisco)
            {
                matrizDisco[fila][0]= disco.getCodigo();
                matrizDisco[fila][1]= disco.getNombre();
                matrizDisco[fila][2]= String.valueOf(disco.getPrecio());
                matrizDisco[fila][3]= disco.getArtista();
                matrizDisco[fila][4]= String.valueOf(disco.getAnnio());
                fila++;
            }
            modelo = new DefaultTableModel(matrizDisco,titulos);
            tblDisco.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
                                            

    }//GEN-LAST:event_btnListarDiscoActionPerformed
    private void limpiarControles()
    {
        txtCodigoInsertar.setText("");
        txtNombreInsertar.setText("");
        txtPrecioInsertar.setText("");
        txtArtistaInsertar.setText("");
        txtAnnioInsertar.setText("");
        txtDimensionesInsertar.setText("");
        txtProductoInsertar.setText("");
    }
    
    
    private void txtNumeroVentaInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroVentaInsertarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroVentaInsertarActionPerformed

    private void txtIngresarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIngresarVentaActionPerformed
        try{
           Date date = txtFechaInsertar.getDate();
           Venta venta = new Venta();
           venta.setNumero(Integer.valueOf(txtNumeroVentaInsertar.getText()));
           venta.setFecha(txtFechaInsertar.getDate());
           venta.producto.setCodigo(txtProductoInsertar.getText());
           IngresarVenta con  = new IngresarVenta();
           //falta verificar que el código ingresado exista. probablemente un método buscarProducto().
           con.insertarVenta(venta,idInterno);
           JOptionPane.showMessageDialog(null, "Venta ingresada");
           limpiarControles();
           idInterno++;
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
        
    }//GEN-LAST:event_txtIngresarVentaActionPerformed

    private void txtImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImprimirActionPerformed
        txaImprimirVenta.setText("");
        IngresarVenta listarventa = new IngresarVenta();
        int subTotal = 0;
        try {
            if(txtNumeroVentaInsertar.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null,"Ingrese un número de venta a consultar");
            }
            else
            {
            ArrayList<Venta> ventaActual = listarventa.ventaNumVenta(Integer.valueOf(txtNumeroVentaInsertar.getText()));
            txaImprimirVenta.append("Venta actual: "+txtNumeroVentaInsertar.getText()+"\n");
            for(Venta vta: ventaActual)
            {
                Disco producto = new Disco();
                producto = listarventa.buscarProducto(vta.getProducto().getCodigo());
                txaImprimirVenta.append("Código Producto: "+vta.getProducto().getCodigo() +"\n");
                txaImprimirVenta.append("Nombre Producto: "+producto.getNombre()+"\n");
                txaImprimirVenta.append("Precio Producto: "+producto.getPrecio()+"\n");
                txaImprimirVenta.append("Fecha agregado: "+vta.getFecha() +"\n");
                txaImprimirVenta.append("   ---"+"\n");
                subTotal = subTotal + producto.getPrecio();
            }
            txaImprimirVenta.append("_______________________"+"\n");
            txaImprimirVenta.append("SUBTOTAL: $"+ subTotal +"\n\n");

            if(subTotal>=20000)
            {
                txaImprimirVenta.append("Se aplicó un descuento de 10% por comprar más de $20.000!\n\n");
            }
            txaImprimirVenta.append("TOTAL A PAGAR: $"+listarventa.calcularTotalConDescuento(subTotal)+"\n");
            if(subTotal == 0){
                txaImprimirVenta.append("Esta venta no existe!\n");
            }
            }
            
            //MantenedorProducto listarproducto = new MantenedorProducto();
            //for(Venta vta:listarventa.listarVenta())
            //{
            // txaImprimirVenta.append(vta.toString());
            //for (Album album:vta.listarproducto() )
            //{
            //txaImprimirVenta.append(album.toString());
        } catch (SQLException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_txtImprimirActionPerformed

    private void btnBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProductoActionPerformed
        try {
            MantenedorProducto con = new MantenedorProducto();

            if (radPoster.isSelected()) {
                Poster poster = con.buscarPoster(txtCodigoInsertar.getText());
                if (poster.getDimension() != null) {
                    txtNombreInsertar.setText(poster.getNombre());
                    txtPrecioInsertar.setText(String.valueOf(poster.getPrecio()));
                    txtDimensionesInsertar.setText(poster.getDimension());
                    txtArtistaInsertar.setText("");
                    txtAnnioInsertar.setText("");
                } else {
                            {
                                JOptionPane.showMessageDialog(null, "No se encontro el poster con  ese codigo");
                            }
                }
            } else if (radDisco.isSelected()) {
                Disco disco = con.buscarDisco(txtCodigoInsertar.getText());
                if (disco.getArtista() != null) {
                    txtNombreInsertar.setText(disco.getNombre());
                    txtPrecioInsertar.setText(String.valueOf(disco.getPrecio()));
                    txtArtistaInsertar.setText(disco.getArtista());
                    txtAnnioInsertar.setText(String.valueOf(disco.getAnnio()));
                    txtDimensionesInsertar.setText("");
                } else {
                    JOptionPane.showMessageDialog(null, "No se encontro el disco con  ese codigo");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Debe ingresar un codigo y seleccionar el tipo de producto");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnBuscarProductoActionPerformed

    private void btnEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProductoActionPerformed
        try{
            MantenedorProducto con = new MantenedorProducto();
            //el valor int devuelve e metodo eliminar es distinto de cero
            if(con.eliminar(txtCodigoInsertar.getText())!=0)
            {
                JOptionPane.showMessageDialog(null, "Producto eliminado");
                limpiarControles();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Producto no encntrado para eliminar");
            }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnEliminarProductoActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
   
        MantenedorProducto con = new MantenedorProducto();
try{
        if (radPoster.isSelected()) 
            {
            Poster poster = new Poster();
            poster.setCodigo(txtCodigoInsertar.getText());
            poster.setNombre(txtNombreInsertar.getText());
            poster.setPrecio(Integer.valueOf(txtPrecioInsertar.getText()));
            poster.setDimension(txtDimensionesInsertar.getText());
            
            if (con.modificarPoster(poster) != 0) 
            {
                JOptionPane.showMessageDialog(null, "Producto modificado");
                limpiarControles();
            } else 
            {
                JOptionPane.showMessageDialog(null, "No existe producto para modificar");
            }
            }
    

        else if (radDisco.isSelected ()) 
            {
            Disco disco = new Disco();
            disco.setCodigo(txtCodigoInsertar.getText());
            disco.setNombre(txtNombreInsertar.getText());
            disco.setPrecio(Integer.valueOf(txtPrecioInsertar.getText()));
            disco.setArtista(txtArtistaInsertar.getText());
            disco.setAnnio(Integer.valueOf(txtAnnioInsertar.getText()));
            
            if (con.modificarDisco(disco) != 0) 
            {
                JOptionPane.showMessageDialog(null, "Producto modificado");
                limpiarControles();
            } else 
            {
                JOptionPane.showMessageDialog(null, "No existe producto para modificar");
            }
            }

    
        else {
                JOptionPane.showMessageDialog(null, "Debe buscar el producto y seleccionar el tipo de producto");
            }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }


    }//GEN-LAST:event_btnModificarActionPerformed

    private void txtCodigoInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoInsertarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoInsertarActionPerformed

    private void tblPosterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPosterMouseClicked
        // Cuando el ususario haga click en la tabla
        try {
            int fila = tblPoster.getSelectedRow();
            txtCodigoInsertar.setText(tblPoster.getValueAt(fila, 0).toString());
            txtNombreInsertar.setText(tblPoster.getValueAt(fila, 1).toString());
            txtPrecioInsertar.setText(tblPoster.getValueAt(fila, 2).toString());
            txtDimensionesInsertar.setText(tblPoster.getValueAt(fila, 3).toString());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }


    }//GEN-LAST:event_tblPosterMouseClicked

    private void tblDiscoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDiscoMouseClicked
        // Cuando el ususario haga click en la tabla
        try {
            int fila = tblDisco.getSelectedRow();
            txtCodigoInsertar.setText(tblDisco.getValueAt(fila, 0).toString());
            txtNombreInsertar.setText(tblDisco.getValueAt(fila, 1).toString());
            txtPrecioInsertar.setText(tblDisco.getValueAt(fila, 2).toString());
            txtArtistaInsertar.setText(tblDisco.getValueAt(fila, 3).toString());
            txtAnnioInsertar.setText(tblDisco.getValueAt(fila, 4).toString());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }//GEN-LAST:event_tblDiscoMouseClicked

    private void btnListarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarVentaActionPerformed
        txaRegistroVentas.setText("");
        IngresarVenta listarVenta = new IngresarVenta();
        RegistroVentas regVenta = new RegistroVentas();
        int numVent;
        int subTotal = 0;
        try {
            ArrayList<Venta> listNumVenta = regVenta.listNumVenta();
            for (Venta numV : listNumVenta) {
                numVent = numV.getNumero();
                ArrayList<Venta> ventaActual = listarVenta.ventaNumVenta(numVent);
                txaRegistroVentas.append("Numero de Venta: " + numVent + "\n\n");
                for (Venta vta : ventaActual) {
                    Disco producto = new Disco();
                    producto = listarVenta.buscarProducto(vta.getProducto().getCodigo());
                    txaRegistroVentas.append("Código Producto: " + vta.getProducto().getCodigo() + "\n");
                    txaRegistroVentas.append("Nombre Producto: " + producto.getNombre() + "\n");
                    txaRegistroVentas.append("Precio Producto: " + producto.getPrecio() + "\n");
                    txaRegistroVentas.append("Fecha agregado: " + vta.getFecha() + "\n");
                    txaRegistroVentas.append("   ---" + "\n");
                    subTotal = subTotal + producto.getPrecio();
                }
                txaRegistroVentas.append("_______________________" + "\n");
                txaRegistroVentas.append("SUBTOTAL: $" + subTotal + "\n\n");

                if (subTotal >= 20000) {
                    txaRegistroVentas.append("Se aplicó un descuento de 10% por comprar más de $20.000!\n\n");
                }
                txaRegistroVentas.append("TOTAL A PAGAR: $" + listarVenta.calcularTotalConDescuento(subTotal) + "\n");
                txaRegistroVentas.append("_______________________" + "\n");
                txaRegistroVentas.append("_______________________" + "\n");
                subTotal = 0;
            }
        } catch (SQLException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnListarVentaActionPerformed

    private void btnIngresoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresoUsuarioActionPerformed
        try {
            if (ingUs.IngresoUs(txtIngresoUsuario.getText(), pwdIngresoContrasena.getText())) {
                tabPane.enable(true);
                JOptionPane.showMessageDialog(null, "Bienvenido, " + txtIngresoUsuario.getText() + "!");
                lblMensajeIngreso.setVisible(false);
                txtIngresoUsuario.setText("");
                pwdIngresoContrasena.setText("");
            } else {
                lblMensajeIngreso.setVisible(true);
                lblMensajeIngreso.setText("Usuario o contraseña incorrecta");
            }
        } catch (SQLException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnIngresoUsuarioActionPerformed

    private void txtIngresoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIngresoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIngresoUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new NewJFrame().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel asas;
    private javax.swing.JButton btnBuscarProducto;
    private javax.swing.JButton btnEliminarProducto;
    private javax.swing.JButton btnIngresoUsuario;
    private javax.swing.JButton btnInsertarProducto;
    private javax.swing.JButton btnListarDisco;
    private javax.swing.JButton btnListarPoster;
    private javax.swing.JButton btnListarVenta;
    private javax.swing.JButton btnModificar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblMensajeIngreso;
    private javax.swing.JPasswordField pwdIngresoContrasena;
    private javax.swing.JRadioButton radDisco;
    private javax.swing.JRadioButton radPoster;
    private javax.swing.JTabbedPane tabPane;
    private javax.swing.JTable tblDisco;
    private javax.swing.JTable tblPoster;
    private javax.swing.JTextArea txaImprimirVenta;
    private javax.swing.JTextArea txaRegistroVentas;
    private javax.swing.JTextField txtAnnioInsertar;
    private javax.swing.JTextField txtArtistaInsertar;
    private javax.swing.JTextField txtCodigoInsertar;
    private javax.swing.JTextField txtDimensionesInsertar;
    private com.toedter.calendar.JDateChooser txtFechaInsertar;
    private javax.swing.JButton txtImprimir;
    private javax.swing.JButton txtIngresarVenta;
    private javax.swing.JTextField txtIngresoUsuario;
    private javax.swing.JTextField txtNombreInsertar;
    private javax.swing.JTextField txtNumeroVentaInsertar;
    private javax.swing.JTextField txtPrecioInsertar;
    private javax.swing.JTextField txtProductoInsertar;
    // End of variables declaration//GEN-END:variables
}
